/*
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */

import java.util.LinkedList;

public class P002 {
	public static void main(String[] args) {
		LinkedList<Integer> evens = new LinkedList<Integer>();
		int a = 1, b = 2, total = 0;
		evens.add(2);
		while (a + b <= 4000000) {
			int c = a + b;
			if (c % 2 == 0) {
				evens.add(c);
			}
			a = b;
			b = c;
		}
		for (Integer i : evens) {
			total += i;
		}
		System.out.println(total);
	}
}
