import java.util.TreeSet;

/*
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 * 
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 * 
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 * 
 * What is the value of the first triangle number to have over five hundred divisors?
 */
public class P012 {
	public static void main(String[] args) {
		long i = 1, sum = 1;
		while (true) {
			i++;
			sum += i;
			long max = (long) Math.sqrt(sum);
			TreeSet<Long> factors = new TreeSet<Long>();
			for (long j = 1; j < max; j++) {
				if (sum % j == 0) {
					factors.add(j);
					factors.add(sum / j);
				}
			}
			if (factors.size() > 500) {
				System.out.println(sum);
				return;
			}
		}
	}
}